### ISSUE TITLE
Crashes Sublime

### ISSUE THREAD

**Issue by lmartins** [P233/Syntax-highlighting-for-Sass#10]
For some reason this syntax mode crashes Sublime every time.
I've used for some a while but suddenly it started causing crashes. I had to remove every plugin and install one by one to isolate the issue. 

Since then, and after I reinstalled Sublime, i've managed to cause the crashes again by installing this again.

Is there anything I can do to help identify what may be the cause?

**Comment by P233** [comment]
This package has been rewritten from scratch and released a Sublime Text 3 only version. The Sublime Text 2 version is no longer supported.

If you still have a crash issue on Sublime Text 3, please open a new issue.

All the best :)
