### ISSUE TITLE
Not working "Goto definition" in sublime text 3

### ISSUE THREAD

**Issue by Sinled** [P233/Syntax-highlighting-for-Sass#15]
I am missing this feature in sass, it works fine with less bundle https://github.com/danro/LESS-sublime but not in sass, i tried to modify `Symbol List - Selectors.tmPreferences` file, but no avail. May be i am missing something?

**Comment by P233** [comment]
This package has been rewritten from scratch and released a Sublime Text 3 only version. Now, only Sass functions and mixins have the "Goto Definition" support.
