### ISSUE TITLE
Code completion & Emmet

### ISSUE THREAD

**Issue by ahmedelgabri** [P233/Syntax-highlighting-for-Sass#17]
I'm using [Emmet](http://docs.emmet.io/) _ex Zen Coding_ & the code completion was working with SCSS & Sass files without a problem when I was a different Sass package. after I installed this package Code completion is not working in SCSS as it used to be.

**Comment by olafgleba** [comment]
@P233 Can confirm that setting `show_css_completions` to `false` within user `Emmet.sublime-settings` plus installing Emmet CSS snippets get the autocompletion back to work again.

**Comment by P233** [comment]
This package is no longer to astrict the working scope of snippets or completions, and all built-in completions were removed. I rewrite this package in order to focus on highlighting syntax only.
