### ISSUE TITLE
Not working in Sublime text 3

### ISSUE THREAD

**Issue by jitendravyas** [P233/Syntax-highlighting-for-Sass#18]
I installed this in my Sublime Text 3 Build 3047 but not getting syntax highlighting for my .scss files

**Comment by TheDutchCoder** [comment]
I have a similar issue, though there are no errors.

I can set a .scss file to use the SCSS syntax, or do it for all files, but only the current file will use the correct highlighting until I quit ST3.

When I relaunch, it's all gone again, very annoying :(

**Comment by zirexba** [comment]
Thanx @Fugaz1 "Open Package Control and then Enable Package, then choose SCSS and finally View -> Syntax -> Open all -> SCSS."

This worked in my case.

**Comment by wowissu** [comment]
my highlight was working , but auto-completion only working on syntax Sass not syntax SCSS.

**Comment by xttn** [comment]
You can install https://github.com/P233/Syntax-highlighting-for-Sass, it working for me!

**Comment by P233** [comment]
This package has been rewritten from scratch and released a Sublime Text 3 only version. If you still have any issues with Sublime Text 3, please open a new issue.
