### ISSUE TITLE
Periods in class selectors are not supported

### ISSUE THREAD

**Issue by firstinflight** [P233/Syntax-highlighting-for-Sass#33]
I've been using the excellent Base16 Twilight Dark color scheme, and have found that while periods in class selectors are supported in CSS files, they aren't supported in Sass files.

I believe this is supported in CSS by the Attribute ID (either _entity.other.attribute-name.id_ or _punctuation.definition.entity_—my guess is the latter).

**CSS (notice the blue period between the "a" and the "cta-button" class):**
![class punctuation in css](https://cloud.githubusercontent.com/assets/7158504/2691628/8d7a0c62-c386-11e3-9a4d-497f717340b2.png)

**Sass (period between "a" and the "custom" class is the same color as the class):**
![class punctuation in sass](https://cloud.githubusercontent.com/assets/7158504/2691630/9d62d622-c386-11e3-9235-6d98e1092492.png)

**Comment by P233** [comment]
This package considers the `.` is part of the class selector as the `#` is part of the id selector and the `::` is part of the pseudo-element selector.  So they shouldn't be highlighted in a different colour.

Highlighting Sass selectors also need to consider interpolations,  e.g. `.class-#{$variable}`, and highlight the punctuations and selector name in the same colour can make things easier :D
