### ISSUE TITLE
Starting Directive with @ adds another @

### ISSUE THREAD

**Issue by lonesome-rider** [P233/Syntax-highlighting-for-Sass#45]
When I start writing a directive with the @ sign and then the completion appears, and I press enter, it adds another @ sign and then I get something lie "@@each". I'm use to write the directives starting with the @ sign always, and not just writing the directive name, I don't know if you could figure out a way to fix this, or I don't know if there's a way and I'm missing it.

Thank you

**Comment by P233** [comment]
This package is no longer to astrict the working scope of snippets or completions, and all built-in completions were removed. I rewrite this package in order to focus on highlighting syntax only.

Sorry for the inconvenience.
