### ISSUE TITLE
Ignore Built-in Completion Packages settings not working

### ISSUE THREAD

**Issue by benfrain** [P233/Syntax-highlighting-for-Sass#47]
I don't think the `ignored_packages` settings are working correctly.

I have added these to my ignored packages:

```
"SHS-At-Rule",
"SHS-Bourbon",
"SHS-Bourbon-Neat",
"SHS-Compass-Mixins",
"SHS-Compass-Variables",
"SHS-CSS-Properties",
"SHS-CSS-Property-Values",
"SHS-Sass-Functions"
```

But I still see autocompletions I don't want.

However, if I go to `/Application\ Support/Sublime\ Text\ 3/Packages/Syntax\ Highlighting\ for\ Sass/Completions` and physically delete the folders in there – autocompletions then work as expected.

**Comment by P233** [comment]
I am sorry for the late reply and the inconvenience. Those built-in completions have been removed from the Sublime Text 3 version.
