### ISSUE TITLE
Error loading syntax file "Packages/SCSS/SCSS.tmLanguage"

### ISSUE THREAD

**Issue by TheDutchCoder** [P233/Syntax-highlighting-for-Sass#50]
Seems like there's a wrong path in this package throwing this error in ST3 on Windows 7.
The package is not called "SCSS" in my folder, but "Syntax highlighting for Sass".

It throws the error on every startup, quite anooying :)

**Comment by P233** [comment]
It looks like Sublime Text was trying to highlight a `.scss` file by using the SCSS package, but can not find it. If you have multiple Sass highlighting packages installed and want to set a primary. You could open any `.scss` file and click `View -> Syntax -> Open all with current extension as` and then choose a package name.

Sorry, the name of this package is a little bit annoying :(, as it's already resisted in Package Control, it's better not to change the name. Open the Command Palette (shift + super + p) and type `scss` `sass` will switch syntax package. This might be a better way :)

**Comment by TheDutchCoder** [comment]
It's the only one I have installed, so that can't be the issue.
I've noticed quite some differences between Mac and Windows as well, but that might (partially) be due to emmet, will have to look into that.

The problem went away after a reboot of the OS btw, so maybe it was a ST issue?
