### ISSUE TITLE
Parent Selector: Invalid syntax highlighting with BEM standards

### ISSUE THREAD

**Issue by benjamincudi** [P233/Syntax-highlighting-for-Sass#53]
When referencing the parent selector, the package is highlighting any non-recognized selector/element as invalid. Unless what follows is a recognized HTML element, or follows recognized selectors, it highlights as invalid even though compilation supports the syntax.
![invalid syntax](https://cloud.githubusercontent.com/assets/3100291/7639963/fe2bfa98-fa4d-11e4-8afe-9a9f14e6a8b2.png)

**Comment by P233** [comment]
This should be fixed in the new version :)
