### ISSUE TITLE
Extension populating multiple errors & warnings in Problems window.

### ISSUE THREAD

**Issue by andrew-serrano** [P233/Syntax-highlighting-for-Sass#56]
OS: macOS Sierra 10.12.1
Vscode: Version 1.6.1 (1.6.1)

For some reason when I had this extension enabled it would trigger a lot of errors and warnings when I was editing my SASS/SCSS files. In result would cause my vscode to crash and since there is no way from me preventing this because I work on a lot of clients files with vscode, therefore , resulting in multiple errors/warnings.

This extension worked fine for the longest time until yesterday. Thank you for your time.

**Comment by P233** [comment]
Sorry for the late reply. This is a Sublime Text package, I don't think it is supported by VS Code :(
