### ISSUE TITLE
this package is causing a bug for HTML files

### ISSUE THREAD

**Issue by aziz** [P233/Syntax-highlighting-for-Sass#60]
see this thread
sublimehq/Packages/issues/958#issuecomment-298939785

**Comment by P233** [comment]
Thanks, I believe it is improved in the latest version (v1.2.1). and sorry for the late reply.

**Comment by michaelblyons** [comment]
As the reporter of sublimehq/Packages#958, I believe I can confirm that <kbd>cmd</kbd>+<kbd>P</kbd>,<kbd>@</kbd>

- no longer includes extraneous entries and
- no longer breaks CSS selector names into their component parts.

👍
