### ISSUE TITLE
Flexbox property 'order' gets different highlight

### ISSUE THREAD

**Issue by L5eoneill** [P233/Syntax-highlighting-for-Sass#63]
For some reason, in the theme I'm using, a file blah.scss having style:
`input {
  order: 1;
}`
has just the word "order" in bright pink background (white font) -- though only when not selected.

This magenta background is also on a fragment identified with:
`&__svg` (so, compiles to classname .blah__svg)
A regular 'svg' style is not seen as an error.
A later directive `@extend %blah__svg;` also does not raise a syntax error highlight.

Looks like your sass highlighter thinks these are invalid. But they are not. The file compiles to css just fine.
'order' is valid if in a flex directive
&__svg is not a selector of an svg tag, but BEM name concatenation

**Comment by P233** [comment]
Thanks. This package has been rewritten from scratch and released a Sublime Text 3 only version.  

Could you please double check if these issues still happened in the new version?

**Comment by L5eoneill** [comment]
Looks good. Thanks!
