### ISSUE TITLE
latest update completely broke highlight

### ISSUE THREAD

**Issue by MartinFugess** [P233/Syntax-highlighting-for-Sass#65]
<img src="http://www.gfdesign.cz/subscss.png">

**Comment by leereichardt** [comment]
It has also broken the Goto Symbol window. It no longer only displays the function list, it displays every use of every keyword of every function

**Comment by tedc** [comment]
And all the CSS autocompletions no longer work. 
Please fix it.

**Comment by P233** [comment]
Hi @MartinFugess,  I have pushed an update a few hours ago. Could you double check if the property name is highlighted as in the old version? Thanks

**Comment by P233** [comment]
@tedc Could you let me know which autocompletions you are using? The built-in completions of the old version has been removed. And I think and tested the Emmet plugin works great for providing CSS completions.

**Comment by MartinFugess** [comment]
current state after last update [27.11.2017 / 14:55]:
<img src="http://www.gfdesign.cz/wrong-scss.png">

<a href="https://github.com/MartinFugess/my-sublime-config/tree/master/Packages/Syntax%20Highlighting%20for%20Sass">3 years old version</a>
 with correct highlighting:
<img src="http://www.gfdesign.cz/good-scss.png">

**Comment by tedc** [comment]
@P233 I'm using Emmet. If I switch syntax highlighting to SCSS  autocompletions stops working. With SASS highlighting checked, everything goes fine.
<img width="354" alt="screenshot 2017-11-27 15 08 55" src="https://user-images.githubusercontent.com/61338/33270654-1031b4f4-d385-11e7-9ca8-f52f5df4ce2a.png">
<img width="345" alt="screenshot 2017-11-27 15 09 10" src="https://user-images.githubusercontent.com/61338/33270655-105ecf16-d385-11e7-8e6d-96354a8fa85d.png">

**Comment by iamsisar** [comment]
there are also scope issues with non-spaced values after property name..

![screen shot 2017-11-27 at 15 38 37](https://user-images.githubusercontent.com/6459637/33272030-3877d688-d389-11e7-9836-86390b132a4e.jpg)

**Comment by P233** [comment]
@MartinFugess In the new version, pseudo class and pseudo element have a new scope name `entity.other.pseudo-class.css.sass` which is inherited from the default Sublime Text CSS package. So it may not be highlighted in some colour schemes but be highlighted is some other colour schemes, I am not very sure. I am just trying to respect the scope naming of the Default CSS package.

Comma is not highlighted as in the old version.

**Comment by mugukamil** [comment]
I also have issues with last update...

if I commented some rule, it comments all lines down...

![image](https://user-images.githubusercontent.com/4193470/33272768-3586d0d8-d39c-11e7-908e-26db91d4cf71.png)

**Comment by P233** [comment]
@tedc That's strange because I just tested and the emmet popup works in SCSS syntax but not in Sass syntax.Actually, if I type "dn" and press tab in Sass syntax, it still completes "display: none" only the popup window doesn't disappear.

I'll keep looking for a solution. Sorry for the inconvenience.

**Comment by P233** [comment]
@mugukamil I just pushed a quick fix. Sorry for the inconvenience.

**Comment by MartinFugess** [comment]
I use default monokai scheme with adaptive theme on latest sublime version [3.0, 3143].
Old version yours plugin highlight correct pseudoclass and pseudoelements, new version not.
For example, the each is also wrong highligted.
<img src="http://www.gfdesign.cz/each-scss.png">

**Comment by dallington** [comment]
@MartinFugess I'm going through the same thing :s

**Comment by P233** [comment]
@MartinFugess @dallington I just pushed another update to fix the variables within `@each`. Please wait for the package control update and take a look.

@iamsisar The non-spaced value issue is also fixed in the latest version.

**Comment by amr789** [comment]
please can you explain  this 's extension in the video tutorial I don't know  how I can use this's  the extension  thank you

**Comment by P233** [comment]
@amr789 You don't have to learn anything to use this plugin. Install this plugin through the package control, then open any `.sass` or `.scss` files, the syntax should be get highlighted.

**Comment by P233** [comment]
@tedc Is your issues solved? Could you check the `css_completions_scope` field of your emmet settings file and make sure the `source.scss` scope is in the list?

I just noticed the `source.sass` scope is not included by default, so the emmet CSS completions don't pop up in `.sass` files.

I am thinking about maybe adding `source.scss - comment - variable - keyword.control - entity.other` to the `css_completions_scope`filed could solve your issue.

**Comment by tedc** [comment]
@P233 yes, css completions now work fine but, before this update, completions worked also with sass/scss variables and all the other strings used in the same file I was working with. Now they didn't suggest/complete any of these.
