### ISSUE TITLE
Publish a ST2 version

### ISSUE THREAD

**Issue by oilvier** [P233/Syntax-highlighting-for-Sass#66]
Hi,

First of all, thank you for your work.

Since your last update, the package is not working at all with Sublime Text 2.

I understand the need for you to maintain only one version, but can you at least leave the old version for ST2 users ?
It's ok if we don't have updates, we just want to use the package as it was before this update.

Thanks in advance.

**Comment by P233** [comment]
Thanks. I have submitted a pull request to https://github.com/wbond/package_control_channel/pull/6755, Once it is merged, the Package Control should distribute different branch of this repo based on the Sublime Text version.

**Comment by oilvier** [comment]
Great, thank you !
