### ISSUE TITLE
Latest version broke Symbol Browser

### ISSUE THREAD

**Issue by leereichardt** [P233/Syntax-highlighting-for-Sass#68]
The latest version has completely broken the symbol browser in ST3 where the window is filled with everything

WITHOUT:
<img width="592" alt="screenshot 2017-11-28 11 57 35" src="https://user-images.githubusercontent.com/1117892/33293933-5f633760-d433-11e7-97eb-169e8cfcb9d9.png">

Installed: 
<img width="596" alt="screenshot 2017-11-28 11 56 57" src="https://user-images.githubusercontent.com/1117892/33293912-4bfed71a-d433-11e7-8b49-6d8f47d710a1.png">

As you can see with it being installed, it's completely filled the symbol browser with everything single variable or mention of a variable in the current file

**Comment by P233** [comment]
Sorry for the issue and my late reply. I added too many things to the symbols list. I'll remove everything else in the symbols list except the `mixin` and `function` definition. Does that sound good? Or what other elements would you like to list in the symbols list?

**Comment by leereichardt** [comment]
Is it possible to a set a scope as well, as this is affecting non-scss files? Mixins and functions are a good idea though.

**Comment by evandrocoan** [comment]
This was also reported on the Sublime Text forum:

1. https://forum.sublimetext.com/t/goto-symbol-not-working/33653 Goto Symbol not working?

The user had to revert Sublime Text to a clean install, and reintroduce his packages until find out this package was causing the problem.

**Comment by FichteFoll** [comment]
Your preferences selector was the following:
```
<string>entity.name.tag, entity.other.attribute-name.id, entity.other.attribute-name.class, variable</string>
```

Any region matching that selector in *any view* would get added to the symbol list. Notably, each `variable` *occurance* (not definition!). By convention, definitions are scoped as `entity.name.<something>`, e.g. `entity.name.function`, and you should look into adding that to the symol list. You should also tie the selector to your syntax only by being more explicit, e.g. `entity.name.function.sass` or `source.sass entity.name`.

**Comment by P233** [comment]
I am really sorry about the issue. I have removed my stupid preferences, therefore only mixin and function definitions can be listed in the symbols list.

**Comment by leereichardt** [comment]
Great thanks,
