### ISSUE TITLE
entity.tag with pseudo element is not scoped correctly when indented

### ISSUE THREAD

**Issue by iamsisar** [P233/Syntax-highlighting-for-Sass#71]
Please look at the attachment for clearer explanation 

![screen shot 2017-12-07 at 10 51 20](https://user-images.githubusercontent.com/6459637/33709228-feb4f384-db3c-11e7-8691-f69eb4ed5b74.jpg)

Please note that "one letter" tags works well.

**Comment by P233** [comment]
Thank you. I have fixed this issue in the lasted version. Please wait for the package control update.
