### ISSUE TITLE
GoTo Symbol (CMD + R) no longer yields any results

### ISSUE THREAD

**Issue by ewohlken** [P233/Syntax-highlighting-for-Sass#75]
GoTo Symbol (CMD + R) no longer yields any results in a sass file with this package installed. Not sure when this broke, but I used to use it all the time to navigate selectors

**Comment by P233** [comment]
I will add the "Goto Symbol" support for Type/ID/Class selectors. Is there anything else you would recommend to add to the symbols list? variable? Thanks.

**Comment by anmith** [comment]
Hi,
IMHO variables may be a touch to much, but maybe as configurable option?

**Comment by P233** [comment]
Thanks. I think I will only add the Type/ID/Class selectors support for now. I didn't find a way to dynamically add or remove elements from the symbols list with Sublime Text APIs. Variables and other elements can be manually added to https://github.com/P233/Syntax-highlighting-for-Sass/blob/master/Preferences/Goto%20Symbol.tmPreferences#L8

The package will be updated in a few hours.
