### ISSUE TITLE
Incorrect highlighting for "footer" type selector

### ISSUE THREAD

**Issue by Domii894** [P233/Syntax-highlighting-for-Sass#76]
The `footer` property doesn't have the correct syntax highlighting for SCSS and Sass.

![image](https://user-images.githubusercontent.com/4848555/35460978-20e47134-02e6-11e8-9abd-d03d5430e8c6.png)
As far as I know, `footer` should have the same highlighting as `header`.

Maybe `footer` should be added to the match-lists at

https://github.com/P233/Syntax-highlighting-for-Sass/blob/7861a053a6eacf19a7f0fbabd98d2afb4767a882/Syntaxes/SCSS.sublime-syntax#L48

and

https://github.com/P233/Syntax-highlighting-for-Sass/blob/7861a053a6eacf19a7f0fbabd98d2afb4767a882/Syntaxes/Sass.sublime-syntax#L51

**Comment by P233** [comment]
Sorry, that's my mistake. I will add it and release soon.
