### ISSUE TITLE
Headings highlights are broken

### ISSUE THREAD

**Issue by CodeartistSerge** [P233/Syntax-highlighting-for-Sass#79]
For some reason the highlights for headings h2-h6 are broken. h1 is fine, tho. Any idea what's wrong? I didn't install or change anything, it just stopped working today.

Tried to reinstall sass package, but still no luck. Confirmed that SCSS syntax is in use.

![default](https://user-images.githubusercontent.com/17958648/35600583-71636286-067a-11e8-8c8e-b539f7daa96a.png)

**Comment by P233** [comment]
Sorry for my mistake. It has been fixed in the `v1.2.3` version.
