### ISSUE TITLE
Not working with ST2

### ISSUE THREAD

**Issue by oilvier** [P233/Syntax-highlighting-for-Sass#80]
Hi,

The package seems to have disappear from the package folder, showing this error on start : 

> error: Error loading syntax file "Packages/Syntax Highlighting for Sass/Syntaxes/SCSS.tmLanguage": Error parsing plist xml: Failed to open file In file "Packages/Syntax Highlighting for Sass/Syntaxes/SCSS.tmLanguage"

I can't find it in "Package Control: Install package" list either.

**Comment by marcoliverteschke** [comment]
My colleague has the same issue.

> I can't find it in "Package Control: Install package" list either.

I think the package itself is still registered as being installed. You can remove the package. Afterwards it will be available for installation again, but reinstalling does not appear to fix the error message.

**Comment by oilvier** [comment]
After digging further, I think the plugin has just changed its name to "Sass".

If you change the default syntax highlighting to "_Sass > Sass/SCSS_" with "_Open all with current extension as..._" you shouldn't have the error anymore.
Be careful to apply to every Sass file already open in ST though (or close them all before doing the change).
