### ISSUE TITLE
Fix some highlighting

### ISSUE THREAD

**Issue by dannysmc95** [P233/Syntax-highlighting-for-Sass#81]
Hi there,

I love this package but I mean, since you've updated it, it doesn't highlight the following:

* Pseudo classes, like `:hover`, `:before`, and `:after`,
* It no longer highlights variables, example: `$font-family`,

Please please please fix this as this was some of the most useful parts of the highlighting!

Thanks,
Danny

**Comment by P233** [comment]
Thanks. The pseudo classes/elements and variables are actually matched correctly. They may not be assigned a color by some color schemes.

Have you tried other color schemes? or you could fork your favorite color scheme and add color support for [the corresponding scope](https://github.com/P233/Syntax-highlighting-for-Sass#scopes-list).

Sorry, I can't make this package to work well with every color schemes.

**Comment by P233** [comment]
Hi @dannysmc95, I just updated the variable scope, so variables will be highlighted as same as the original Sass package. But I remain the pseudo class/element scope to keep it same as the default CSS package.

**Comment by dannysmc95** [comment]
Hi @P233, thank you for that update, was amazing, and has worked. I have a few questions still as this is the main package I used for all development and a lot of devs in our company use it on a religious basis haha, so I was wondering how come when it auto fills the attributes, it does not add the semi colon anymore? Is this something from your package?

Also in terms of the colour scheme, how would I go about on changing this, sorry for the newbie question. I use sublime daily, but I still have no idea how to amend the colour schemes, I am using the afterglow package, monokai theme, I mean, this did match and colour the pseudo elements before your update to the package? so are you definitely sure?

Thanks for the quick response!!
