### ISSUE TITLE
Error loading syntax file

### ISSUE THREAD

**Issue by kevnk** [P233/Syntax-highlighting-for-Sass#83]
![](https://files.classyllama.com/bc9abf9a/sass-syntax-error.png)

**Comment by P233** [comment]
I think it's caused by some settings cache because this package has changed its name to "Sass". Please manually change the syntax to "Sass" > "SCSS", or maybe with the "Open all with current extension as..." option.

**Comment by kevnk** [comment]
I tried this and it didn't work. I even tried setting it to something else, restarting sublime, and then set it back to Sass > SCSS and that didn't work either. Maybe something in the .sublime-workspace file?

**Comment by kevnk** [comment]
> Please manually change the syntax to "Sass" > "SCSS", or maybe with the "Open all with current extension as..." option.

After doing this, I closed every SCSS file I had open in my project (which reset everything SCSS-related in the .sublime-workspace project file) so when I restarted Sublime, the popup did not show.
