### ISSUE TITLE
Variable highlighting gone

### ISSUE THREAD

**Issue by ShaneRSChroll** [P233/Syntax-highlighting-for-Sass#84]
Variables used to highlight as orange and they no longer highlight this way anymore. Would very much like this back as the white color they are now is extremely hard to differentiate between.

**Comment by P233** [comment]
Thanks, I've updated the variable highlighitng in `v1.2.4`.

**Comment by ShaneRSChroll** [comment]
Ah, thank you so much! I went to use it and was confused why my variables
were white lol. It just makes seeing them in larger projects easier when
changing things if they are orange and stand out! Thanks again!
