### ISSUE TITLE
Error with new version

### ISSUE THREAD

**Issue by theimaginaire** [P233/Syntax-highlighting-for-Sass#86]
Hi,

My version of the plugin updated and now doesn't highlight any of our .scss files and comes up with the following error every time we open an scss file:

`Error loading syntax file "Packages/Syntax Highlighting for Sass/Syntaxes/SCSS.sublime-syntax": Unable to read Packages/Syntax Highlighting for Sass/Syntaxes/SCSS.sublime-syntax`

I've tried completely removing and reinstalling but still getting the same issues.

Using Sublime Text 3 build 3143 with standard theme etc.

**Comment by AdamGerthel** [comment]
Same here:
![screen shot 2018-02-02 at 16 58 05](https://user-images.githubusercontent.com/1490370/35742283-490fb99e-083a-11e8-9d65-537906c20ab7.png)

**Comment by P233** [comment]
Please see #83. I hope that could help.

**Comment by AdamGerthel** [comment]
#83 helped

**Comment by theimaginaire** [comment]
Thanks, that's worked for me too.
